### ISSUE TITLE
Git moving away from SHA1 discussions 

### ISSUE THREAD

**Issue by chriscool** [multiformats/c-multihash#1]
The latest discussion about this subject:

http://thread.gmane.org/gmane.comp.version-control.git/299687/

There have been many other discussions about this over the years, but the latest one above is a good starting point. It mentions multihash.

**Comment by chriscool** [comment]
An old discussion from 2006:

http://thread.gmane.org/gmane.comp.version-control.git/26106/

just to show that people have been thinking about this for a long time, but not much has been done yet.

**Comment by chriscool** [comment]
If we want c-multihash to be used by Git, we should be aware of the following:
- Git is very unlikely to add any build dependency. It is considered great that it depends on very few things and if anything people want to reduce the number of dependencies.
- Some subdirectories in the Git source tree are synchronized from other external repos, but they are not core to the project.
- Git uses its own version of Sharness, as Sharness was created by extracting the Git test framework from Git.

**Comment by Kubuxu** [comment]
Currently I am making c-multihash as small and requiring as little dependencies as possible.

Also I am trying to follow git's coding guide and limit usage of new coding styles (not using C99 libs).

The plan is to make it a static library and allow for embedding the whole repository.

**Comment by jbenet** [comment]
those links are down, sadly, due to gmane's problem. can we get the archive on ipfs or something?

**Comment by jbenet** [comment]
they may be in wayback machine

**Comment by jbenet** [comment]
@Kubuxu found http://www.spinics.net/lists/git/msg281246.html

Can someone please make a list of _all_ the relevant emails so i can read them? with Gmane down, all these other sites are not easy to search...

**Comment by chriscool** [comment]
On https://public-inbox.org/git/CAPp-Vrb_n6z39RLHZ4AeUaBFiJfL3_xX8Utfq7%2BbTgzZrza58Q%40mail.gmail.com/
all the other emails in the thread are after the first one.

**Comment by chriscool** [comment]
A discussion from 2006 (linked in the first email of the above thread) is the following:

https://public-inbox.org/git/44F1DCB7.6020804%40garzik.org/

**Comment by chriscool** [comment]
Another one is:

https://public-inbox.org/git/5468C33E.2080108%40whonix.org/

**Comment by jbenet** [comment]
It's hard to navigate these interfaces, hard to uncover what's in a thread
or not. Could someone more familiar collect all the links to the relevant
emails?

**Comment by rvagg** [comment]
closed due to inactivity, archiving repo
