### ISSUE TITLE
Full parity with go-multihash functionality

### ISSUE THREAD

**Issue by alex-hutton** [multiformats/c-multihash#5]
I have noticed that go-multihash provides additional functionality that c-multihash (and other implementations) do not. This additional functionality appears to be dependended upon by reverse dependencies of go-multihash, such as go-ipld, go-ipfs and go-libp2p.

I also notice a discrepancy between the functionality of go-multihash and js-multihash in that there is functionality provided by js-multihash, which is depended upon by its reverse dependencies, which is not provided by go-multihash.

Here is a list of some of the multihash dependencies that do not seem to be supported by c-multihash:

```
Language: golang

repo: go-libp2p
file: /p2p/protocol/relay/relay.go
multihash dependencies:
NewReader()
NewWriter()
Multihash()

repo: go-ipld
file: ipld.go
multihash dependencies:
FromB58String()

repo: go-ipfs
file: /namesys/routing.go
multihash dependencies:
FromB58String()
Cast()

repo: js-ipfs
file:/src/core/components/block.js
multihash dependencies:
FromB58String()
file: /src/core/components/files.js
multihash dependencies:
toB58String()
file: /src/core/components/init.js
multihash dependencies:
toB58String()
```

My question is, would pull requests to c-multihash be welcome which implemented this functionality?

**Comment by jmjatlanta** [comment]
I believe that the from/to base 58 is useful. The reader/writer/constructor/cast I have not used, and therefore cannot reply as to their usefulness.

**Comment by Kubuxu** [comment]
Including base58 would more than double size of this package, I think it should be implemented separately as it will be useful in multibase too.

The Reader/Writer is used for hashing itself witch is feature go-multihash.

We have discussed this feature for C implementation and decided that it would be best to split it off to separate project, probably named `c-multihashing` as including hashing algorithms in C isn't as simple as in other languages.

**Comment by rvagg** [comment]
closed due to inactivity, archiving repo
